-- AlterTable
ALTER TABLE "OrderFact" ADD COLUMN IF NOT EXISTS "discountTotal" DOUBLE PRECISION;
ALTER TABLE "OrderFact" ADD COLUMN IF NOT EXISTS "shippingTotal" DOUBLE PRECISION;
ALTER TABLE "OrderFact" ADD COLUMN IF NOT EXISTS "taxTotal" DOUBLE PRECISION;
ALTER TABLE "OrderFact" ADD COLUMN IF NOT EXISTS "unitCount" INTEGER;
