-- Wave A metrics spine: aMER numerator + contribution-margin cost stack.
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "cogsPct" DOUBLE PRECISION;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "paymentFeesPct" DOUBLE PRECISION;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "shippingPct" DOUBLE PRECISION;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "marginOverride" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "SalesDayFact" ADD COLUMN IF NOT EXISTS "newCustomerNetSales" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesDayFact" ADD COLUMN IF NOT EXISTS "returningCustomerNetSales" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "SampleSalesDay" ADD COLUMN IF NOT EXISTS "newCustomerNetSales" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "CashClose" ADD COLUMN IF NOT EXISTS "cogsPct" DOUBLE PRECISION;
ALTER TABLE "CashClose" ADD COLUMN IF NOT EXISTS "paymentFeesPct" DOUBLE PRECISION;
ALTER TABLE "CashClose" ADD COLUMN IF NOT EXISTS "shippingPct" DOUBLE PRECISION;
